# Generated by Django 5.1.2 on 2024-12-01 00:49

import django.db.models.deletion
import userblog.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('likes', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('views', models.IntegerField(default=0, verbose_name='Visualisações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='userblog.category', verbose_name='Categoria')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_users', to=settings.AUTH_USER_MODEL, verbose_name='ID do usuário')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['title', 'created_at', 'published'],
            },
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=userblog.models.upload_media, verbose_name='Arquivo')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='Tipo de mídia')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='userblog.post', verbose_name='ID da publicação')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['post__title', 'media_type', 'file'],
            },
        ),
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Data de publicação')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published')], default='scheduled', max_length=20, verbose_name='Status do agendamento')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='userblog.post', verbose_name='ID do agendamento')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['post__title', 'scheduled_at', 'status'],
            },
        ),
    ]
