# Generated by Django 5.1.2 on 2024-11-24 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postschedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
