# Generated by Django 5.1.2 on 2024-12-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1, verbose_name='DEscrição'),
            preserve_default=False,
        ),
    ]
