# Generated by Django 5.1.2 on 2024-12-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='userblog.category', verbose_name='Categorias'),
        ),
    ]
