# Generated by Django 5.1.2 on 2024-11-24 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0002_alter_postschedule_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='mediablog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
