# Generated by Django 5.1.2 on 2024-12-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblog', '0006_alter_post_state_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
